name: inspector

# Workflow will be triggered when any one of these workflows runs
on:
  workflow_run:
    workflows: 
      [scrape-giant-manual, scrape-ntuc-manual, scrape-shengsiong-manual]
    types: [completed]
        


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a two jobs called "on-success" and "on-failure"
  on-success:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
      - run: echo ${{ github.event.workflows }} ' succeeded.'
  
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps: 
      - run: echo ${{ github.event.workflows }} ' failed.'
