name: inspector

# Workflow will be triggered when any one of these workflows runs
on:
  workflow_run:
    workflows: 
      [scrape-giant-manual, scrape-ntuc-manual, scrape-shengsiong-manual]
    types: [completed]
    


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a two jobs called "on-success" and "on-failure"
  on-success:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
    
      - name: Statement
        run: |
            echo "${{ github.event.workflow.name }} succeeded."
            echo "Workflow file path: ${{ github.event.workflow.path }}"
            echo "${{ github.event.workflow.html_url }}"
  
  
  
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    
    steps: 
            
      - name: Checkout repo content
        uses: actions/checkout@v2
        with:
            token: ${{ secrets.WORKFLOW_TOKEN }}
            
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
            python-version: 3.8.2
            
      - name: Run Python script
        run: |
            echo "${{ github.event.workflow.name }} failed."
            echo "Workflow file path: ${{ github.event.workflow.path }}"
            echo "${{ github.event.workflow.html_url }}"
            export workflow_path=${{ github.event.workflow.path }}
            pip install pyyaml
            python reschedule_next_run.py
      
      - name: Commit and push modified YAML file
        env:
            WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        run: |
            git config user.name "${GITHUB_ACTOR}"
            git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            git add -A
            timestamp=$(date -u)
            git commit -m "${{ github.event.workflow.name }}" 
            git push "https://${GITHUB_ACTOR}:$WORKFLOW_TOKEN@github.com/${GITHUB_REPOSITORY}.git" HEAD:main || exit 0

      
      
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
