name: scrape-shengsiong-manual
on: [workflow_dispatch]
jobs:
  scrape:
    runs-on: macos-latest
    steps:
    - name: checkout repo content
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.6
    - name: setup virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    - name: setup dependencies
      run: |
        pip install -r requirements.txt
        playwright install firefox
    - name: execute spider script to get the latest data
      run: scrapy crawl sg-ov8
      working-directory: ./scraper-files
    - name: Commit and push if repo is modified
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Scraped: [${timestamp}] sg-ov8 (manual)" 
        git push "https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main || exit 0
